export default {
  testEnvironment: 'node',
  testMatch: ['**/__tests__/**/*.test.ts'],
  transform: { '^.+\\.tsx?$': 'ts-jest' },
  roots: ['<rootDir>/packages'],
  moduleFileExtensions: ['ts', 'tsx', 'js', 'jsx', 'json', 'node'],
  testPathIgnorePatterns: ['/node_modules/', '/dist/'],
  collectCoverageFrom: [
    'packages/*/src/**/*.ts',
    'plugins/*/src/**/*.ts',
    '!packages/*/src/**/__tests__/**',
    '!packages/*/src/**/*.test.ts',
    '!plugins/*/src/**/__tests__/**',
    '!plugins/*/src/**/*.test.ts',
  ],
  projects: [
    {
      displayName: 'core',
      testEnvironment: 'node',
      testMatch: ['<rootDir>/packages/core/src/__tests__/**/*.test.ts'],
      transform: { '^.+\\.tsx?$': 'ts-jest' },
      moduleFileExtensions: ['ts', 'tsx', 'js', 'jsx', 'json', 'node'],
      testPathIgnorePatterns: ['/node_modules/', '/dist/'],
    },
    {
      displayName: 'hub',
      testEnvironment: 'node',
      testMatch: ['<rootDir>/packages/hub/src/__tests__/**/*.test.ts'],
      transform: { '^.+\\.tsx?$': 'ts-jest' },
      moduleFileExtensions: ['ts', 'tsx', 'js', 'jsx', 'json', 'node'],
      testPathIgnorePatterns: ['/node_modules/', '/dist/'],
    },
    {
      displayName: 'workflows',
      testEnvironment: 'node',
      testMatch: ['<rootDir>/packages/workflows/src/__tests__/**/*.test.ts'],
      transform: { '^.+\\.tsx?$': 'ts-jest' },
      moduleFileExtensions: ['ts', 'tsx', 'js', 'jsx', 'json', 'node'],
      testPathIgnorePatterns: ['/node_modules/', '/dist/'],
    },
    {
      displayName: 'claude-plugin',
      testEnvironment: 'node',
      testMatch: ['<rootDir>/plugins/syncpulse-claude-plugin/src/__tests__/**/*.test.ts'],
      transform: { '^.+\\.tsx?$': 'ts-jest' },
      moduleFileExtensions: ['ts', 'tsx', 'js', 'jsx', 'json', 'node'],
      testPathIgnorePatterns: ['/node_modules/', '/dist/'],
    },
  ],
};
